name: Release

on:
  push:
    tags:
      - 'v*-alpha.*'  # Only alpha tags
  workflow_dispatch:
    inputs:
      tag:
        description: 'Alpha tag to release (e.g., v1.15.0-alpha.1)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  check-branch:
    name: Check if Alpha Tag is on Develop Branch
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      tag_name: ${{ steps.check.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to check branches

      - name: Check branch and tag
        id: check
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${{ github.event.inputs.tag }}"
          else
            TAG_NAME="${{ github.ref_name }}"
          fi
          
          # Check if tag exists on develop branch
          if git branch -r --contains $TAG_NAME | grep -q "origin/develop"; then
            echo "✅ Tag $TAG_NAME found on develop branch"
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Tag $TAG_NAME not found on develop branch"
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi
          
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

  determine-config:
    name: Determine Build Configuration
    runs-on: ubuntu-latest
    needs: check-branch
    if: needs.check-branch.outputs.should_release == 'true'
    outputs:
      is_alpha: ${{ steps.config.outputs.is_alpha }}
      tag_name: ${{ steps.config.outputs.tag_name }}
    steps:
      - name: Set configuration
        id: config
        run: |
          TAG_NAME="${{ needs.check-branch.outputs.tag_name }}"
          echo "is_alpha=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    needs: [check-branch, determine-config]
    if: needs.check-branch.outputs.should_release == 'true'
    env:
      Q_CLI_ALPHA: ${{ needs.determine-config.outputs.is_alpha == 'true' && '1' || '0' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Intel binary
        run: cargo build --release --target x86_64-apple-darwin --bin chat_cli

      - name: Build Apple Silicon binary
        run: cargo build --release --target aarch64-apple-darwin --bin chat_cli

      - name: Create universal binary
        run: |
          mkdir -p target/universal-apple-darwin/release
          lipo -create -output target/universal-apple-darwin/release/q \
            target/x86_64-apple-darwin/release/chat_cli \
            target/aarch64-apple-darwin/release/chat_cli

      - name: Create DMG package
        run: |
          chmod +x scripts/github-actions/create-macos-dmg.sh
          ./scripts/github-actions/create-macos-dmg.sh

      - name: Generate checksums
        run: |
          if [ "${{ needs.determine-config.outputs.is_alpha }}" = "true" ]; then
            shasum -a 256 target/universal-apple-darwin/release/q > q-alpha-universal-binary.sha256
            shasum -a 256 Amazon-Q-CLI-Alpha-universal.dmg > Amazon-Q-CLI-Alpha-universal.dmg.sha256
          else
            shasum -a 256 target/universal-apple-darwin/release/q > q-universal-binary.sha256
            shasum -a 256 Amazon-Q-CLI-universal.dmg > Amazon-Q-CLI-universal.dmg.sha256
          fi

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-artifacts
          path: |
            target/universal-apple-darwin/release/q
            *.dmg
            *.sha256

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: [check-branch, determine-config]
    if: needs.check-branch.outputs.should_release == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-msvc --bin chat_cli

      - name: Create Windows package
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "q-windows" -Force
          Copy-Item "target\x86_64-pc-windows-msvc\release\chat_cli.exe" "q-windows\q.exe"
          Copy-Item "README.md", "LICENSE.MIT", "LICENSE.APACHE" "q-windows\"
          
          @"
          Amazon Q CLI Windows Installation Instructions
          
          1. Extract this ZIP to a folder (e.g., C:\Program Files\Amazon Q CLI)
          2. Add the folder to your PATH environment variable
          3. Open a new Command Prompt or PowerShell window
          4. Run: q --version
          
          Note: Windows may show a SmartScreen warning for unsigned software.
          Click "More info" then "Run anyway" to proceed.
          
          For more information: https://github.com/aws/amazon-q-developer-cli
          "@ | Out-File -FilePath "q-windows\INSTALL.txt" -Encoding UTF8
          
          Compress-Archive -Path "q-windows" -DestinationPath "q-windows-x86_64.zip"

      - name: Generate checksums
        shell: powershell
        run: |
          $binaryHash = Get-FileHash "target\x86_64-pc-windows-msvc\release\chat_cli.exe" -Algorithm SHA256
          "$($binaryHash.Hash.ToLower())  chat_cli.exe" | Out-File -FilePath "q-windows-binary.sha256" -Encoding ASCII
          
          $zipHash = Get-FileHash "q-windows-x86_64.zip" -Algorithm SHA256
          "$($zipHash.Hash.ToLower())  q-windows-x86_64.zip" | Out-File -FilePath "q-windows-x86_64.zip.sha256" -Encoding ASCII

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-artifacts
          path: |
            q-windows-x86_64.zip
            q-windows-binary.sha256
            q-windows-x86_64.zip.sha256

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [check-branch, determine-config, build-macos, build-windows]
    if: needs.check-branch.outputs.should_release == 'true'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Generate release notes
        id: release_notes
        run: |
          TAG_NAME="${{ needs.determine-config.outputs.tag_name }}"
          IS_ALPHA="${{ needs.determine-config.outputs.is_alpha }}"
          
          if [ "$IS_ALPHA" = "true" ]; then
            RELEASE_TYPE="Alpha Pre-release"
            STABILITY_WARNING="⚠️ **This is an alpha pre-release** for testing purposes only."
          else
            RELEASE_TYPE="Stable Release"
            STABILITY_WARNING="✅ **This is a stable release** ready for production use."
          fi
          
          cat > release_notes.md << EOF
          # Amazon Q CLI ${TAG_NAME} (${RELEASE_TYPE})
          
          ${STABILITY_WARNING}
          
          ## Cross-Platform Support
          
          This release provides native packages for all major platforms:
          
          ### macOS
          - **Universal Binary**: Works on both Intel and Apple Silicon Macs
          - **Package**: \`$([ "$IS_ALPHA" = "true" ] && echo "Amazon-Q-CLI-Alpha-universal.dmg" || echo "Amazon-Q-CLI-universal.dmg")\` (drag-and-drop installation)
          - **Installation**: Double-click DMG, drag to Applications, right-click → Open (first time)
          
          ### Windows
          - **Architecture**: x86_64 (64-bit Intel/AMD)
          - **Package**: \`q-windows-x86_64.zip\`
          - **Installation**: Extract ZIP, add to PATH, handle SmartScreen warning
          
          ## Security & Verification
          
          All packages include SHA256 checksums for verification:
          
          \`\`\`bash
          # macOS
          shasum -a 256 $([ "$IS_ALPHA" = "true" ] && echo "Amazon-Q-CLI-Alpha-universal.dmg" || echo "Amazon-Q-CLI-universal.dmg")
          
          # Windows
          certutil -hashfile q-windows-x86_64.zip SHA256
          \`\`\`
          
          ## Installation Quick Start
          
          ### macOS
          1. Download \`$([ "$IS_ALPHA" = "true" ] && echo "Amazon-Q-CLI-Alpha-universal.dmg" || echo "Amazon-Q-CLI-universal.dmg")\`
          2. Double-click to mount, drag to Applications
          3. Right-click → Open (bypass Gatekeeper)
          4. Run: \`$([ "$IS_ALPHA" = "true" ] && echo "q-alpha --version" || echo "q --version")\`
          
          ### Windows
          1. Download \`q-windows-x86_64.zip\`
          2. Extract to preferred location
          3. Add directory to PATH
          4. Handle SmartScreen warning (More info → Run anyway)
          5. Run: \`q --version\`
          
          ## Support
          
          - [GitHub Issues](https://github.com/aws/amazon-q-developer-cli/issues)
          - [Documentation](https://github.com/aws/amazon-q-developer-cli)
          - Include \`q --version\` output when reporting issues
          
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.determine-config.outputs.tag_name }}
          name: Amazon Q CLI ${{ needs.determine-config.outputs.tag_name }}
          body_path: release_notes.md
          draft: false
          prerelease: ${{ needs.determine-config.outputs.is_alpha == 'true' }}
          files: |
            *.dmg
            *.zip
            *.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
