name: Release

on:
  push:
    tags:
      - 'v*-alpha.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Alpha tag to release (e.g., v1.13.2-alpha.1)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build-macos:
    name: Build macOS Alpha Release
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-

      - name: Build Intel binary
        run: cargo build --release --target x86_64-apple-darwin --bin chat_cli

      - name: Build Apple Silicon binary
        run: cargo build --release --target aarch64-apple-darwin --bin chat_cli

      - name: Create universal binary
        run: |
          mkdir -p target/universal-apple-darwin/release
          lipo -create -output target/universal-apple-darwin/release/q \
            target/x86_64-apple-darwin/release/chat_cli \
            target/aarch64-apple-darwin/release/chat_cli

      - name: Create DMG package
        run: |
          chmod +x scripts/github-actions/create-macos-dmg.sh
          ./scripts/github-actions/create-macos-dmg.sh

      - name: Generate checksums
        run: |
          shasum -a 256 target/universal-apple-darwin/release/q > q-universal-binary.sha256
          shasum -a 256 Amazon-Q-CLI-universal.dmg > Amazon-Q-CLI-universal.dmg.sha256

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-alpha-release-artifacts
          path: |
            target/universal-apple-darwin/release/q
            Amazon-Q-CLI-universal.dmg
            q-universal-binary.sha256
            Amazon-Q-CLI-universal.dmg.sha256
          retention-days: 30

  create-release:
    name: Create GitHub Alpha Release
    runs-on: ubuntu-latest
    needs: [build-macos]
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Generate release notes
        id: release_notes
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG_NAME="${{ github.event.inputs.tag }}"
          fi
          
          cat > release_notes.md << EOF
          # Amazon Q CLI ${TAG_NAME} (Alpha Pre-release)
          
          ⚠️ **This is an alpha pre-release** built with the new GitHub Actions pipeline. Use for testing only.
          
          ## Installation Instructions
          
          ### macOS
          
          **Option 1: DMG (Recommended)**
          1. Download \`Amazon-Q-CLI-universal.dmg\`
          2. Double-click to mount the disk image
          3. Drag 'q' to Applications folder
          4. Right-click 'q' in Applications → "Open" (first time only)
          5. Click "Open" when prompted about unidentified developer
          
          **Option 2: Direct Binary**
          1. Download \`q\` (universal binary)
          2. Move to /usr/local/bin: \`sudo mv q /usr/local/bin/q\`
          3. Make executable: \`sudo chmod +x /usr/local/bin/q\`
          4. Remove quarantine: \`sudo xattr -d com.apple.quarantine /usr/local/bin/q\`
          
          ## Verification
          
          All packages include SHA256 checksums for verification:
          
          \`\`\`bash
          # macOS DMG
          shasum -a 256 Amazon-Q-CLI-universal.dmg
          
          # macOS Binary
          shasum -a 256 q
          \`\`\`
          
          Compare with the corresponding .sha256 files.
          
          ## Security Notice
          
          These packages are **unsigned** but safe to use. This is normal for open-source software.
          
          - ✅ **Verify checksums** before installation
          - ✅ **Download only** from official GitHub releases  
          - ✅ **Review build logs** in GitHub Actions for transparency
          - ✅ **Source code** is fully open and auditable
          
          ## Alpha Release Notes
          
          This alpha release demonstrates:
          - ✅ Unsigned macOS packages (DMG + universal binary)
          - ✅ SHA256 checksum verification
          - ✅ GitHub Actions automated builds
          - ✅ Universal binary support (Intel + Apple Silicon)
          - ✅ Professional DMG packaging
          
          **Testing Focus:**
          - Installation process on different macOS versions
          - Gatekeeper bypass workflow
          - Binary functionality across architectures
          - DMG mounting and drag-drop installation
          
          **Known Limitations:**
          - Only macOS packages available (Windows/Linux coming later)
          - Alpha quality - use for testing purposes only
          
          ## Feedback
          
          Please report any issues with this alpha release:
          - [GitHub Issues](https://github.com/aws/amazon-q-developer-cli/issues)
          - Tag issues with \`alpha-testing\` label
          
          EOF

      - name: Create Alpha Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}${{ github.event.inputs.tag }}
          name: Amazon Q CLI ${{ github.ref_name }}${{ github.event.inputs.tag }} (Alpha)
          body_path: release_notes.md
          draft: false
          prerelease: true
          files: |
            q
            Amazon-Q-CLI-universal.dmg
            q-universal-binary.sha256
            Amazon-Q-CLI-universal.dmg.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
